services:
  angular_app:
    hostname: angular_app
    container_name: angular_app
    image: angular_app
    build:
      context: .
    ports:
      - "4200:80"
      - "8080:80"
      - "80:80"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - angular_network

networks:
  angular_network:
    name: angular_app_network